### ISSUE TITLE
Turn httpS on

### ISSUE THREAD

**Issue by esquinas** [MalagaMakers/MalagaMakers.github.io#9]
MalagaMakers should use a secure certificate  (http**s** address) because _reasons<sup>**1**</sup>_ 

**1:** SEO, Chrome and other browsers labelling us as dangerous, best practices, :sunglasses: cool-factor...

**Comment by JonasBr68** [comment]
It can be enforced with a setting https://help.github.com/articles/securing-your-github-pages-site-with-https/
Github pages already automatically support https, but can be enforced with this setting. I don’t have access to the settings tab on the repository at github so… Leo? Takes a 20 seconds…

**Comment by xiazek** [comment]
Guys, Done :) 
https://www.malagamakers.com/

<img width="765" alt="captura de pantalla 2018-09-20 a las 8 30 14" src="https://user-images.githubusercontent.com/32790/45799914-6f746d80-bcaf-11e8-9472-f097d1f248da.png">

🎉 
Warm greatings from Kraków !

**Comment by esquinas** [comment]
This is great!

Majiek, it would be awesome if you came visit Malaga on our 4th anniversary in November. 

Thanks a lot. 👍

**Comment by xiazek** [comment]
OH WOW that has been almost 4 years now !!
I wish to come. It might be hard though, as I'm not working remotely atm and have just 2 holidays left in 2018... One day, I'll come !

**Comment by leolara** [comment]
Thank you Maciej 👏

**Comment by partymola** [comment]
Made you a pull request at https://github.com/MalagaMakers/MalagaMakers.github.io/pull/10 , since you are now having mixed-content errors when visiting the site over https, as the google font(s) still are trying to load over http.
